server:
  error:
    include-message: always
  port: 9600


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/loan
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
